confirm(" Aimerais-tu joué le jeux?")
var nom = prompt("Quel est ta bande musicale favorite?");
alert("WOW! " + nom + " eh! mais c'est aussi ma bande musicale favorite Eh!");
var nom = prompt(" Quel est ton animal de compagnie favoris? ");
alert(" awwww tu nas pas pris un peroquet? Je blague! " + nom + " Eh! est aussi mon animal de compagnie favoris! Eh! ");
var nom = prompt("Quels est ton passe temps que tu aime le plus?");
alert(" Incroyable! " + nom + " Eh! est aussi mon passe temps favoris Eh! ");
var nom = prompt("Quel est ton jeux favoris?");
alert(" On se ressamble tellement!" + nom + " Eh! est aussi mon passe temps favoris Eh! ");
 
 
